"""Remove genre animes table

Revision ID: 260340967631
Revises: 69f1d470d9bb
Create Date: 2021-10-11 20:15:46.334556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260340967631'
down_revision = '69f1d470d9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres_animes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres_animes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anime_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], name='genres_animes_anime_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='genres_animes_genre_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='genres_animes_pkey')
    )
    # ### end Alembic commands ###
