"""Add watched episode model

Revision ID: 294c8411effc
Revises: 9e4a06de98ed
Create Date: 2021-10-11 22:44:10.971407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294c8411effc'
down_revision = '9e4a06de98ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched_episodes')
    # ### end Alembic commands ###
