"""Add updated_at column episodes 

Revision ID: 4018d239aaf3
Revises: 702ab1a960c3
Create Date: 2021-10-15 13:01:11.449965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4018d239aaf3'
down_revision = '702ab1a960c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute('UPDATE episodes SET updated_at = created_at WHERE updated_at is NULL')
    op.alter_column('episodes', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'updated_at')
    # ### end Alembic commands ###
