"""Add user favorite model

Revision ID: 686295204d01
Revises: 294c8411effc
Create Date: 2021-10-11 22:54:38.999478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686295204d01'
down_revision = '294c8411effc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_favorites_animes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_favorites_animes')
    # ### end Alembic commands ###
