"""Add updated_at column animes 

Revision ID: 702ab1a960c3
Revises: 994215ae44ee
Create Date: 2021-10-15 12:57:34.106842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702ab1a960c3'
down_revision = '994215ae44ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute('UPDATE animes SET updated_at = created_at WHERE updated_at is NULL')
    op.alter_column('animes', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animes', 'updated_at')
    # ### end Alembic commands ###
