"""Add updated_at column

Revision ID: 994215ae44ee
Revises: 686295204d01
Create Date: 2021-10-15 12:49:27.839489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994215ae44ee'
down_revision = '686295204d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute('UPDATE users SET updated_at = created_at WHERE updated_at is NULL')
    op.alter_column('users', 'updated_at', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
