"""Add updated_at column comments 

Revision ID: bbdb51c7d745
Revises: 4018d239aaf3
Create Date: 2021-10-15 13:05:47.794715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbdb51c7d745'
down_revision = '4018d239aaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute('UPDATE comments SET updated_at = created_at WHERE updated_at is NULL')
    op.alter_column('comments', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'updated_at')
    # ### end Alembic commands ###
